apiVersion: v1
kind: ConfigMap
metadata:
  name: dell-ca-config
  namespace: model-serving
data:
  dell-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIID9TCCAt2gAwIBAgIQQCJAHt6EvM+qnHodlMdVxDANBgkqhkiG9w0BAQsFADCB
    zzELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBVRleGFzMQ8wDQYDVQQHEwZBdXN0aW4x
    HzAdBgNVBAoTFkRlbGwgVGVjaG5vbG9naWVzIEluYy4xJzAlBgNVBAsTHlNlY3Vy
    aXR5IGFuZCBSZXNpbGllbmNlIE9mZmljZTEsMCoGA1UEAxMjRGVsbCBUTFMgRGVj
    cnlwdGlvbiBBdXRob3JpdHkgUFJEMjYxJzAlBgkqhkiG9w0BCQEWGERlbGxfVGVj
    aF9Qcm94eUBEZWxsLmNvbTAeFw0yNjA4MTQwMDAwMDBaFw0yNzAyMjcyMzU5NTla
    MBkxFzAVBgNVBAMTDmh1Z2dpbmdmYWNlLmNvMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA23EnvX3nrB0p770wcc77OWRHXJ0eiUlEecT8cSbrwLBtUDjM
    Nplztm8RNkIEPJILn5aUtX9UMtIdKkByxKB0Mjg3CFnXBE26onL+rnXmN7WeSBe7
    oN8m5CTIijFwkX6xsJE6a/msaR0cqlPRY1hgyCDED/GGLzHhyaVwWmqqKR8nEavI
    feObn2oBLyp+LzENFrvQKCcJrfKvWwO+mTV0apF7mpqFfYLEZIpE6+4GYpMslhge
    6ufpOY9EMChHaglExAssWlbRi8Ury8M3gWKOp4A+LQlwBSrfyVAizggH+fKPKqhu
    KIhU6/w+AigO0k8FkmDvxHqzn255aMVvt2ed4wIDAQABo4GBMH8wHQYDVR0OBBYE
    FMUUdEOUH1B4fW9Ia6iRVUm1uRnJMCsGA1UdEQQkMCKCDmh1Z2dpbmdmYWNlLmNv
    ghAqLmh1Z2dpbmdmYWNlLmNvMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQClwo1RgvEY
    LsS2XfyKZGxFH35GMiAW5a2Th36i39mWYrjFu762kgcXZchJuwC3FqEv8J8Z2gtG
    Ii3QeMWO5WQIXLJf/6doDWX0l/93LIlWYFg+ayfqE1qEN+jvq7qv7pHknhii2Qx8
    RdoSOJr6aqd+NuC1SX2Evibqzj3hEwjc571iI/HOcAF6MaNZN7pSSH+6MP/5hDxL
    g8XaSQHIkdADhCRvAu7RqthPpJrrKckYc0ojkCzRT+3Pj/CWsuX5lTAllOays9Lj
    02mGe6+oDUMQUI+oJ60uKerKVFhqGNQgRQVIDdxJ6p8BgB89waq48y3aWxMJCvfp
    MX4J4ERALsvd
    -----END CERTIFICATE-----
