"""
Main entry point for the Agentic Pipeline Model Deployment System

This script provides the entry point for running the LangGraph-based
multi-agent deployment workflow for Phase 1.

Phase 1 Architecture:
User Request → Primary Agent → Constraint Resolver → Deployment Pipeline → 
CI Agent → Kubernetes Deployment Agent → MicroK8s → vLLM → Inference Endpoint
"""

import asyncio
import sys
from pathlib import Path
from typing import Optional, Dict, Any

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from core.state.models import AgentState
from core.graph.workflow import create_deployment_graph
from core.state.persistence import state_manager
from tools.infrastructure.infrastructure_checker import InfrastructureChecker
from loguru import logger


def setup_logging():
    """Configure logging for the application"""
    logger.remove()
    logger.add(
        sys.stdout,
        format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>",
        level="INFO"
    )
    logger.add(
        "logs/agentic_pipeline.log",
        rotation="10 MB",
        retention="7 days",
        level="DEBUG"
    )


async def check_infrastructure() -> Dict[str, Any]:
    """
    Check infrastructure prerequisites before deployment
    
    Returns:
        Infrastructure check results
    """
    logger.info("=" * 60)
    logger.info("Checking Infrastructure Prerequisites")
    logger.info("=" * 60)
    
    checker = InfrastructureChecker()
    results = checker.check_all()
    
    logger.info("\nInfrastructure Check Results:")
    logger.info("=" * 60)
    
    for component, result in results.items():
        if component == "recommended_deployment_type":
            logger.info(f"\nRecommended Deployment Type: {result}")
        else:
            status = "✅" if result.get("available") else "❌"
            logger.info(f"{status} {component}: {result.get('reason', 'Unknown')}")
            if result.get("details"):
                logger.info(f"   Details: {result.get('details')}")
    
    logger.info("=" * 60)
    
    return results


async def run_deployment(
    model_id: str,
    latency_requirement: Optional[str] = None,
    deployment_type: Optional[str] = None,
    infrastructure_details: Optional[Dict[str, Any]] = None
) -> AgentState:
    """
    Run the deployment workflow using LangGraph
    
    Args:
        model_id: Model identifier (e.g., "Qwen/Qwen2.5-7B")
        latency_requirement: Latency requirement (e.g., "<100ms")
        deployment_type: Deployment type (e.g., "standard", "canary")
        infrastructure_details: Infrastructure specifications
        
    Returns:
        Final agent state with deployment results
    """
    logger.info("=" * 60)
    logger.info("Starting Model Deployment Workflow")
    logger.info("=" * 60)
    logger.info(f"Model ID: {model_id}")
    logger.info(f"Latency Requirement: {latency_requirement or 'Not specified'}")
    logger.info(f"Deployment Type: {deployment_type or 'standard'}")
    logger.info("=" * 60)
    
    # Create the LangGraph workflow
    logger.info("Creating LangGraph workflow...")
    workflow = create_deployment_graph()
    
    # Compile the workflow
    logger.info("Compiling workflow...")
    app = workflow.compile()
    
    # Initialize the agent state
    initial_state = AgentState(
        messages=[],
        deployment_conversation_id="",  # Will be auto-generated by primary agent
        model_id=model_id,
        model_source_path=None,
        latency_requirement=latency_requirement,
        deployment_type=deployment_type,
        infrastructure_details=infrastructure_details or {},
        errors=[],
        current_state="IDLE",
        state_history=[],
        retry_count=0,
        max_retries=3
    )
    
    # Run the workflow
    logger.info("Running LangGraph workflow...")
    try:
        final_state = await app.ainvoke(initial_state)
        logger.info("Workflow completed successfully")
    except Exception as e:
        logger.error(f"Workflow execution failed: {e}")
        raise
    
    # Display results
    logger.info("=" * 60)
    logger.info("Deployment Workflow Results")
    logger.info("=" * 60)
    
    if final_state.get("deployment_conversation_id"):
        logger.info(f"Deployment Conversation ID: {final_state['deployment_conversation_id']}")
    
    if final_state.get("current_state"):
        logger.info(f"Final State: {final_state['current_state']}")
    
    if final_state.get("service_endpoint"):
        logger.info(f"Service Endpoint: {final_state['service_endpoint']}")
    
    if final_state.get("kubernetes_deployment_report"):
        k8s_report = final_state['kubernetes_deployment_report']
        logger.info(f"Kubernetes Deployment Status: {k8s_report.get('deployment_status', 'unknown')}")
        logger.info(f"Summary: {k8s_report.get('summary', 'No summary')}")
    
    if final_state.get("errors"):
        logger.warning(f"Errors encountered: {len(final_state['errors'])}")
        for error in final_state['errors']:
            logger.warning(f"  - {error}")
    
    logger.info("=" * 60)
    
    return final_state


async def main():
    """Main entry point"""
    setup_logging()
    
    logger.info("🚀 Agentic Pipeline - Model Deployment System")
    logger.info("Phase 1: Hugging Face + vLLM + MicroK8s + ArgoCD")
    logger.info("")
    
    # Check infrastructure
    infrastructure_results = await check_infrastructure()
    
    # Determine if we should proceed
    recommended_type = infrastructure_results.get("recommended_deployment_type")
    
    if recommended_type == "insufficient_infrastructure":
        logger.error("❌ Insufficient infrastructure for deployment")
        logger.error("Please install required components before proceeding")
        sys.exit(1)
    
    logger.info(f"\n✅ Infrastructure check passed. Recommended deployment type: {recommended_type}")
    
    # Example deployment configuration
    model_id = "Qwen/Qwen2.5-7B"
    latency_requirement = "<100ms"
    deployment_type = "standard"
    
    infrastructure_details = {
        "gpu_type": "NVIDIA RTX PRO 2000",
        "gpu_memory_gb": 8,
        "gpu_count": 1,
        "cpu_cores": 4,
        "ram_gb": 16
    }
    
    # Run deployment
    try:
        final_state = await run_deployment(
            model_id=model_id,
            latency_requirement=latency_requirement,
            deployment_type=deployment_type,
            infrastructure_details=infrastructure_details
        )
        
        # Check final status
        if final_state.get("current_state") == "DEPLOYED":
            logger.info("✅ Deployment completed successfully!")
            logger.info(f"🎉 Model is available at: {final_state.get('service_endpoint', 'Unknown')}")
        else:
            logger.warning(f"⚠️ Deployment completed with status: {final_state.get('current_state', 'Unknown')}")
            if final_state.get("errors"):
                logger.error("Deployment errors:")
                for error in final_state.get("errors", []):
                    logger.error(f"  - {error}")
    
    except Exception as e:
        logger.error(f"❌ Deployment failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())