import asyncio
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.primary_agent import PrimaryAgent
from core.state.models import AgentState
from core.config.settings import settings


async def test_primary_agent():
    """Test the Primary Agent with deployment orchestration"""
    
    # Initialize agent
    agent = PrimaryAgent()
    
    # Create test state with deployment requirements
    test_state = AgentState(
        messages=[],
        deployment_conversation_id="",  # Will be auto-generated by agent
        model_id="fraud_model_v3",
        model_source_path=None,
        latency_requirement="<100ms",
        deployment_type="canary",
        infrastructure_details={
            "gpu_type": "NVIDIA A100",
            "gpu_memory_gb": 80,
            "gpu_count": 2,
            "cpu_cores": 64,
            "ram_gb": 256
        },
        errors=[]
    )
    
    print("Testing Primary Agent - Deployment Orchestration")
    print("=" * 60)
    print(f"Model ID: {test_state['model_id']}")
    print(f"Latency Requirement: {test_state['latency_requirement']}")
    print(f"Deployment Type: {test_state['deployment_type']}")
    print(f"Using Configuration:")
    print(f"  - Container Registry: {settings.default_container_registry}")
    print(f"  - Organization: {settings.default_organization}")
    print(f"  - Base Image: {settings.default_base_image}")
    print(f"  - Service Endpoint Base: {settings.service_endpoint_base_url}")
    print(f"  - Serving Framework Priority: {settings.serving_framework_priority}")
    print()
    
    # Run orchestration
    result_state = await agent.orchestrate_deployment(test_state)
    
    # Display results
    print("=" * 60)
    print("Deployment Orchestration Results")
    print("=" * 60)
    
    if result_state.get('deployment_conversation_id'):
        print(f"Deployment Conversation ID: {result_state['deployment_conversation_id']}")
    
    if result_state.get('decomposed_sub_agent_tasks'):
        print(f"\nDecomposed Sub-Agent Tasks ({len(result_state['decomposed_sub_agent_tasks'])}):")
        for i, task in enumerate(result_state['decomposed_sub_agent_tasks'], 1):
            print(f"\n  Task {i}: {task['task_name']}")
            print(f"    ID: {task['task_id']}")
            print(f"    Assigned to: {task['assigned_to']}")
            print(f"    Priority: {task['priority']}")
            print(f"    Dependencies: {task['dependencies'] if task['dependencies'] else 'None'}")
            print(f"    Description: {task['description'][:80]}...")
    
    if result_state.get('final_deployment_report'):
        report = result_state['final_deployment_report']
        print(f"\nFinal Deployment Report:")
        print(f"  Status: {report['deployment_status']}")
        print(f"  Timestamp: {report['deployment_timestamp']}")
        print(f"  Service Endpoint: {report['service_endpoint']}")
        print(f"  Latency Requirement: {report['latency_requirement']}")
        print(f"  Deployment Type: {report['deployment_type']}")
        
        print(f"\n  CI Pipeline:")
        print(f"    Pipeline ID: {report['ci_pipeline']['pipeline_id']}")
        print(f"    GitHub Repository: {report['ci_pipeline']['github_repository']}")
        print(f"    Workflows Created: {', '.join(report['ci_pipeline']['workflows_created'])}")
        print(f"    Verification Status: {report['ci_pipeline']['pipeline_verification']['overall_status']}")
        
        print(f"\n  Deployment Pipeline:")
        print(f"    Deployment ID: {report['deployment_pipeline']['deployment_id']}")
        print(f"    ArgoCD Application: {report['deployment_pipeline']['argocd_application']}")
        print(f"    Container Image: {report['deployment_pipeline']['container_image']}")
        print(f"    ArgoCD Verification: {report['deployment_pipeline']['argocd_verification']['overall_status']}")
        print(f"    Deployment Status: {report['deployment_pipeline']['deployment_status']}")
        
        print(f"\n  Summary:")
        print(f"    {report['summary']}")
        
        print(f"\n  Tasks Executed: {report['tasks_executed']}")
    else:
        print("No final deployment report generated - check logs for errors")


async def test_primary_agent_with_constraint_report():
    """Test Primary Agent with constraint resolver report integration"""
    
    # Initialize agent
    agent = PrimaryAgent()
    
    # Create test state with constraint resolver report
    test_state = AgentState(
        messages=[],
        deployment_conversation_id="",  # Will be auto-generated
        model_id="qwen2.5-7b",
        model_source_path=None,
        latency_requirement="<50ms",
        deployment_type="standard",
        infrastructure_details={
            "gpu_type": "NVIDIA A100",
            "gpu_memory_gb": 40,
            "gpu_count": 1,
            "cpu_cores": 32,
            "ram_gb": 128
        },
        constraint_resolver_report={
            "model_id": "qwen2.5-7b",
            "overall_confidence_score": 85,
            "quantization_levels_possible": [
                {"level": "FP16", "size_gb": 14.5, "speed_multiplier": 1.0, "accuracy_loss": "none"},
                {"level": "INT8", "size_gb": 7.2, "speed_multiplier": 1.5, "accuracy_loss": "minimal"}
            ],
            "parallelization_possible": {
                "tensor": True,
                "pipeline": False,
                "expert": False,
                "data": True
            },
            "weight_format": "safetensors",
            "engine_type": "vllm",
            "deployment_feasible": True,
            "recommendations": [
                "Use vLLM with tensor parallelism for optimal performance",
                "Consider INT8 quantization to reduce memory footprint"
            ]
        },
        errors=[]
    )
    
    print("\n" + "=" * 60)
    print("Testing Primary Agent with Constraint Resolver Report")
    print("=" * 60)
    print(f"Model ID: {test_state['model_id']}")
    print(f"Latency Requirement: {test_state['latency_requirement']}")
    print(f"Constraint Confidence: {test_state['constraint_resolver_report']['overall_confidence_score']}%")
    print(f"Recommended Engine: {test_state['constraint_resolver_report']['engine_type']}")
    print()
    
    # Run orchestration
    result_state = await agent.orchestrate_deployment(test_state)
    
    # Display results
    if result_state.get('final_deployment_report'):
        report = result_state['final_deployment_report']
        print(f"\nFinal Deployment Report:")
        print(f"  Service Endpoint: {report['service_endpoint']}")
        print(f"  CI Pipeline ID: {report['ci_pipeline']['pipeline_id']}")
        print(f"  Deployment ID: {report['deployment_pipeline']['deployment_id']}")
        print(f"  ArgoCD Status: {report['deployment_pipeline']['argocd_verification']['overall_status']}")
        print(f"  Summary: {report['summary']}")


async def test_primary_agent_different_latency_requirements():
    """Test Primary Agent with different latency requirements"""
    
    agent = PrimaryAgent()
    
    test_cases = [
        {
            "model_id": "low_latency_model",
            "latency_requirement": "<50ms",
            "deployment_type": "standard"
        },
        {
            "model_id": "standard_model",
            "latency_requirement": "<100ms",
            "deployment_type": "canary"
        },
        {
            "model_id": "high_latency_model",
            "latency_requirement": "<200ms",
            "deployment_type": "blue_green"
        }
    ]
    
    print("\n" + "=" * 60)
    print("Testing Primary Agent with Different Latency Requirements")
    print("=" * 60)
    
    for i, test_case in enumerate(test_cases, 1):
        print(f"\nTest Case {i}:")
        print(f"  Model: {test_case['model_id']}")
        print(f"  Latency: {test_case['latency_requirement']}")
        print(f"  Deployment: {test_case['deployment_type']}")
        
        test_state = AgentState(
            messages=[],
            deployment_conversation_id="",
            model_id=test_case['model_id'],
            latency_requirement=test_case['latency_requirement'],
            deployment_type=test_case['deployment_type'],
            errors=[]
        )
        
        result_state = await agent.orchestrate_deployment(test_state)
        
        if result_state.get('final_deployment_report'):
            report = result_state['final_deployment_report']
            print(f"  Result:")
            print(f"    CI Pipeline: {report['ci_pipeline']['pipeline_id']}")
            print(f"    Deployment: {report['deployment_pipeline']['deployment_id']}")
            print(f"    ArgoCD: {report['deployment_pipeline']['argocd_verification']['overall_status']}")
            print(f"    Endpoint: {report['service_endpoint']}")


if __name__ == "__main__":
    print("=" * 60)
    print("Test 1: Primary Agent Basic Deployment Orchestration")
    print("=" * 60)
    asyncio.run(test_primary_agent())
    
    print("\n" + "=" * 60)
    print("Test 2: Primary Agent with Constraint Resolver Report")
    print("=" * 60)
    asyncio.run(test_primary_agent_with_constraint_report())
    
    print("\n" + "=" * 60)
    print("Test 3: Primary Agent with Different Latency Requirements")
    print("=" * 60)
    asyncio.run(test_primary_agent_different_latency_requirements())
